//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleriWinFormApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public int Car_Id { get; set; }
        public int Customer_Id { get; set; }
        public int Department_Id { get; set; }
        public int Personel_Id { get; set; }
        public string Sale_Time { get; set; }
        public string Sale_Price { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Department Department { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
